import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, Check, Database, FileJson, Layers3, Play, Plus, RefreshCw, RotateCcw, Search, Trash2, X } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { api } from "../services/api";
import { useApp } from "../context/AppContext";
import JsonEditor from "../components/JsonEditor";
import StatCard from "../components/StatCard";

function useRequest(loader, initial) {
    const [state, setState] = useState({ data: initial, loading: true, error: "" });
    const reload = async () => {
        setState(current => ({ ...current, loading: true, error: "" }));
        try { setState({ data: await loader(), loading: false, error: "" }); }
        catch (error) { setState({ data: initial, loading: false, error: error.message }); }
    };
    useEffect(() => { reload(); }, []);
    return { ...state, reload };
}

function PageState({ loading, error, onRetry }) { if (loading) return <div className="empty-state"><RefreshCw className="spin" size={20} />Loading engine data...</div>; if (error) return <div className="empty-state error-panel"><strong>Could not load this view</strong><span>{error}</span>{onRetry && <button className="button secondary" onClick={onRetry}>Retry</button>}</div>; return null; }
function SectionHeader({ title, children }) { return <div className="section-header"><div><h2>{title}</h2></div><div className="section-actions">{children}</div></div>; }
function Empty({ children }) { return <div className="empty-state"><FileJson size={22} /><span>{children}</span></div>; }

export function Dashboard() {
    const docs = useRequest(api.getAll, []); const indexes = useRequest(api.getIndexes, { indexes: [] }); const txns = useRequest(api.getTransactions, { transactions: [] });
    if (docs.loading || indexes.loading) return <PageState loading />;
    const records = docs.data || []; const keys = records.length ? Object.keys(records[0]).filter(key => key !== "id").slice(0, 3).join(" / ") : "No fields discovered";
    return <div className="page-stack"><div className="welcome"><div><div className="eyebrow">ENGINE OVERVIEW</div><h2>Good morning, operator.</h2><p>A clear view of the JSON engine, its active data, and durable work.</p></div><Link className="button primary" to="/documents"><FileJson size={16} />Inspect documents <ArrowRight size={16} /></Link></div><div className="stats-grid"><StatCard label="Documents" value={records.length} detail="in users collection" icon={FileJson} tone="blue" /><StatCard label="Indexes" value={indexes.data.indexes?.length || 0} detail="available lookup paths" icon={Layers3} tone="orange" /><StatCard label="Active transactions" value={txns.data.transactions?.length || 0} detail="currently staged" icon={Activity} tone="green" /><StatCard label="Engine" value="ONLINE" detail={keys} icon={Database} tone="pink" /></div><div className="dashboard-grid"><div className="panel"><SectionHeader title="Collection snapshot"><Link className="text-link" to="/documents">Open collection <ArrowRight size={14} /></Link></SectionHeader><div className="snapshot-row"><div className="collection-avatar">U</div><div><strong>users</strong><span>{records.length} records · JSON storage</span></div><span className="pill green">ACTIVE</span></div><div className="field-list">{(records[0] ? Object.keys(records[0]) : ["id", "name", "email"]).slice(0, 5).map(field => <span key={field}><b>{field}</b><small>{field === "id" ? "number" : "dynamic"}</small></span>)}</div></div><div className="panel accent-panel"><div className="eyebrow">ENGINE NOTES</div><h3>One API, many primitives.</h3><p>Query planning, hash indexes, transactions, and write-ahead logging stay behind the Express boundary. This console only speaks JSON to that API.</p><Link className="text-link" to="/query">Open query console <ArrowRight size={14} /></Link></div></div></div>;
}

export function Databases() { const { selectedCollection, setSelectedCollection } = useApp(); return <div className="page-stack"><SectionHeader title="Databases"><button className="button secondary" disabled title="Database management endpoints are not exposed by the current HTTP API"><Plus size={16} />Create database</button></SectionHeader><div className="notice-panel"><Database size={20} /><div><strong>Current HTTP API scope</strong><p>The Express API currently exposes the default data directory as the <b>users</b> collection. The underlying engine supports databases and collections through its TCP server; this view keeps that boundary explicit.</p></div></div><div className="resource-grid"><div className="resource-card selected"><div className="resource-icon"><Database size={19} /></div><div><strong>FlexStore data</strong><span>Default database directory</span><small>1 collection exposed over HTTP</small></div><span className="pill blue">CURRENT</span><button className="button secondary small" onClick={() => { setSelectedCollection("users"); window.location.href = "/collections"; }}>Open <ArrowRight size={14} /></button></div></div></div>; }

export function Collections() { const { setSelectedCollection } = useApp(); return <div className="page-stack"><SectionHeader title="Collections"><button className="button secondary" disabled><Plus size={16} />Create collection</button></SectionHeader><div className="resource-grid"><div className="resource-card selected"><div className="resource-icon"><FileJson size={19} /></div><div><strong>users</strong><span>General-purpose JSON records</span><small>Available through the current Express API</small></div><span className="pill green">READY</span><button className="button primary small" onClick={() => { setSelectedCollection("users"); window.location.href = "/documents"; }}>Open <ArrowRight size={14} /></button></div></div></div>; }

export function Documents() {
    const { setNotice } = useApp(); const docs = useRequest(api.getAll, []); const [search, setSearch] = useState(""); const [editor, setEditor] = useState(null); const [json, setJson] = useState("{\n  \"name\": \"\",\n  \"email\": \"\"\n}");
    const records = useMemo(() => { const needle = search.toLowerCase(); return (docs.data || []).filter(record => !needle || JSON.stringify(record).toLowerCase().includes(needle)); }, [docs.data, search]);
    const save = async () => { try { const value = JSON.parse(json); if (editor === "new") await api.insertDocument(value); else await api.updateDocument(editor.id, value); setEditor(null); await docs.reload(); setNotice({ message: editor === "new" ? "Document inserted." : "Document updated." }); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    const remove = async id => { if (!window.confirm(`Delete document ${id}?`)) return; try { await api.deleteDocument(id); await docs.reload(); setNotice({ message: "Document deleted." }); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    return <div className="page-stack"><SectionHeader title="users"><div className="search-box"><Search size={16} /><input placeholder="Search JSON documents" value={search} onChange={event => setSearch(event.target.value)} /></div><button className="button primary" onClick={() => { setJson("{\n  \"name\": \"\",\n  \"email\": \"\"\n}"); setEditor("new"); }}><Plus size={16} />Insert document</button></SectionHeader><PageState loading={docs.loading} error={docs.error} onRetry={docs.reload} />{!docs.loading && !docs.error && <div className="panel table-panel"><div className="table-meta"><span>{records.length} matching documents</span><button className="icon-button" onClick={docs.reload} title="Refresh"><RefreshCw size={16} /></button></div>{records.length ? <div className="table-wrap"><table><thead><tr><th>ID</th><th>Preview</th><th>Fields</th><th>Actions</th></tr></thead><tbody>{records.map(record => <tr key={record.id}><td><code>{record.id}</code></td><td><strong>{record.name || "Untitled record"}</strong><small>{record.email || "No email field"}</small></td><td><code>{Object.keys(record).filter(key => key !== "id").join(", ") || "empty"}</code></td><td><div className="row-actions"><button className="icon-button" onClick={() => { setJson(JSON.stringify(record, null, 2)); setEditor(record); }} title="Edit"><FileJson size={16} /></button><button className="icon-button danger" onClick={() => remove(record.id)} title="Delete"><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div> : <Empty>No documents match this search.</Empty>}</div>}{editor && <div className="modal-backdrop"><div className="modal"><div className="modal-header"><div><div className="eyebrow">{editor === "new" ? "NEW DOCUMENT" : `DOCUMENT ${editor.id}`}</div><h3>{editor === "new" ? "Insert JSON" : "Edit JSON"}</h3></div><button className="icon-button" onClick={() => setEditor(null)}><X size={18} /></button></div><JsonEditor value={json} onChange={setJson} /><div className="modal-actions"><button className="button secondary" onClick={() => setEditor(null)}>Cancel</button><button className="button primary" onClick={save}><Check size={16} />Save document</button></div></div></div>}</div>;
}

export function QueryConsole() { const { setNotice } = useApp(); const [query, setQuery] = useState("{\n  \"name\": \"Arjun\"\n}"); const [result, setResult] = useState(null); const [plan, setPlan] = useState(null); const run = async explain => { try { const filter = JSON.parse(query); if (explain) setPlan(await api.explain(filter)); else setResult(await api.query(filter)); } catch (error) { setNotice({ type: "error", message: error.message }); } }; return <div className="page-stack"><div className="console-grid"><div className="panel query-editor"><div className="eyebrow">FILTER / USERS</div><h3>Build a query</h3><JsonEditor value={query} onChange={setQuery} label="Mongo-style filter" /><div className="button-row"><button className="button primary" onClick={() => run(false)}><Play size={16} />Execute</button><button className="button secondary" onClick={() => run(true)}>Explain plan</button></div></div><div className="panel results-panel"><SectionHeader title={plan ? "Execution plan" : "Results"}>{(result || plan) && <button className="icon-button" onClick={() => { setResult(null); setPlan(null); }} title="Clear"><RotateCcw size={16} /></button>}</SectionHeader>{plan ? <pre className="json-output">{JSON.stringify(plan, null, 2)}</pre> : result ? <><div className="result-count">{result.count ?? result.data?.length ?? 0} documents returned</div><pre className="json-output">{JSON.stringify(result.data ?? result, null, 2)}</pre></> : <Empty>Execute a filter to see records or inspect its query plan.</Empty>}</div></div></div>; }

export function Indexes() { const { setNotice } = useApp(); const indexes = useRequest(api.getIndexes, { indexes: [] }); const [field, setField] = useState(""); const create = async () => { try { await api.createIndex(field.trim()); setField(""); await indexes.reload(); setNotice({ message: `Index created on ${field}.` }); } catch (error) { setNotice({ type: "error", message: error.message }); } }; const remove = async value => { try { await api.deleteIndex(value); await indexes.reload(); } catch (error) { setNotice({ type: "error", message: error.message }); } }; return <div className="page-stack"><SectionHeader title="Indexes"><div className="inline-form"><input placeholder="field name" value={field} onChange={event => setField(event.target.value)} /><button className="button primary" onClick={create} disabled={!field.trim()}><Plus size={16} />Create index</button></div></SectionHeader><PageState loading={indexes.loading} error={indexes.error} onRetry={indexes.reload} />{!indexes.loading && <div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Field</th><th>Type</th><th>Status</th><th /></tr></thead><tbody>{(indexes.data.indexes || []).map(index => <tr key={index.field}><td><strong>{index.field}</strong></td><td><span className="pill blue">HASH</span></td><td><span className="pill green">ACTIVE</span></td><td><button className="icon-button danger" onClick={() => remove(index.field)}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>{!indexes.data.indexes?.length && <Empty>No indexes yet. Add one to make equality queries faster.</Empty>}</div>}</div>; }

export function Schema() { const docs = useRequest(api.getAll, []); const fields = useMemo(() => { const map = new Map(); (docs.data || []).forEach(record => Object.entries(record).forEach(([key, value]) => { if (!map.has(key)) map.set(key, Array.isArray(value) ? "array" : value === null ? "null" : typeof value); })); return [...map.entries()]; }, [docs.data]); return <div className="page-stack"><SectionHeader title="Schema"><span className="pill orange">INFERRED FROM DATA</span></SectionHeader><div className="notice-panel"><FileJson size={20} /><div><strong>No schema HTTP endpoint is currently registered</strong><p>This read-only view infers observed fields from the live collection. Validation still happens inside the engine when a schema is configured.</p></div></div><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Field</th><th>Observed type</th><th>Required</th></tr></thead><tbody>{fields.map(([field, type]) => <tr key={field}><td><strong>{field}</strong></td><td><code>{type}</code></td><td>{field === "id" ? <span className="pill green">YES</span> : <span className="pill">OPTIONAL</span>}</td></tr>)}</tbody></table></div></div></div>; }

export function Transactions() { const { setNotice } = useApp(); const transactions = useRequest(api.getTransactions, { transactions: [] }); const [selected, setSelected] = useState(null); const begin = async () => { try { const data = await api.beginTransaction(); await transactions.reload(); setSelected(data.transaction); setNotice({ message: "Transaction started." }); } catch (error) { setNotice({ type: "error", message: error.message }); } }; const finish = async (action) => { try { await api[action](selected.id); setSelected(null); await transactions.reload(); setNotice({ message: `Transaction ${action === "commitTransaction" ? "committed" : "rolled back"}.` }); } catch (error) { setNotice({ type: "error", message: error.message }); } }; return <div className="page-stack"><SectionHeader title="Transactions"><button className="button primary" onClick={begin}><Plus size={16} />Begin transaction</button></SectionHeader><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>ID</th><th>Status</th><th>Operations</th><th /></tr></thead><tbody>{(transactions.data.transactions || []).map(txn => <tr key={txn.id}><td><button className="text-link" onClick={() => setSelected(txn)}>{txn.id}</button></td><td><span className="pill orange">{txn.status || "ACTIVE"}</span></td><td>{txn.operations?.length || 0}</td><td><button className="button secondary small" onClick={() => setSelected(txn)}>Inspect</button></td></tr>)}</tbody></table></div>{!transactions.data.transactions?.length && <Empty>No active transactions.</Empty>}</div>{selected && <div className="modal-backdrop"><div className="modal compact"><div className="modal-header"><div><div className="eyebrow">TRANSACTION</div><h3>{selected.id}</h3></div><button className="icon-button" onClick={() => setSelected(null)}><X size={18} /></button></div><pre className="json-output">{JSON.stringify(selected, null, 2)}</pre><div className="modal-actions"><button className="button secondary" onClick={() => finish("rollbackTransaction")}><RotateCcw size={16} />Rollback</button><button className="button primary" onClick={() => finish("commitTransaction")}><Check size={16} />Commit</button></div></div></div>}</div>; }

export function Logs() { const wal = useRequest(api.getWal, { records: [] }); return <div className="page-stack"><SectionHeader title="Write-ahead log"><button className="button secondary" onClick={wal.reload}><RefreshCw size={16} />Refresh log</button></SectionHeader><div className="panel table-panel"><div className="table-meta"><span>{wal.data.count || wal.data.records?.length || 0} durable records</span><span className="pill green">RECOVERY ENABLED</span></div><PageState loading={wal.loading} error={wal.error} onRetry={wal.reload} />{!wal.loading && !wal.error && (wal.data.records?.length ? <pre className="json-output">{JSON.stringify(wal.data.records, null, 2)}</pre> : <Empty>The WAL is clean. New transaction records will appear here.</Empty>)}</div></div>; }
