import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRight, Database, FileJson, Layers3, Play, Plus, RefreshCw, Trash2, X } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../services/api";
import { useApp } from "../context/AppContext";
import JsonEditor from "../components/JsonEditor";
import StatCard from "../components/StatCard";

function Header({ title, children }) { return <div className="section-header"><h2>{title}</h2><div className="section-actions">{children}</div></div>; }
function Empty({ children }) { return <div className="empty-state"><FileJson size={20} />{children}</div>; }
function ScopeRequired() { return <Empty>Select a database and collection in the top bar to continue.</Empty>; }

export function Dashboard() {
    const { databases, selectedDatabase, selectedCollection } = useApp(); const [status, setStatus] = useState(null); const [count, setCount] = useState(0);
    useEffect(() => { api.getStatus().then(setStatus).catch(() => setStatus(null)); }, []);
    useEffect(() => { if (selectedDatabase && selectedCollection) api.getDocuments(selectedDatabase, selectedCollection).then(data => setCount(data.count || 0)).catch(() => setCount(0)); }, [selectedDatabase, selectedCollection]);
    return <div className="page-stack"><div className="welcome"><div><div className="eyebrow">ENGINE OVERVIEW</div><h2>FlexStore control room.</h2><p>Inspect durable JSON data, query plans, and operational state.</p></div><Link className="button primary" to="/documents">Inspect documents <ArrowRight size={15} /></Link></div><div className="stats-grid"><StatCard label="Databases" value={databases.length} detail="persisted databases" icon={Database} tone="blue" /><StatCard label="Documents" value={count} detail={selectedCollection || "no collection selected"} icon={FileJson} tone="orange" /><StatCard label="Storage" value={status?.storage || "..."} detail={`Server ${status?.server || "..."}`} icon={Database} tone="green" /><StatCard label="Recovery" value={status?.recovery || "..."} detail="write-ahead logging" icon={Layers3} tone="pink" /></div></div>;
}

export function Databases() {
    const { databases, selectedDatabase, setSelectedDatabase, refreshDatabases, setNotice } = useApp(); const [name, setName] = useState("");
    const create = async () => { try { await api.createDatabase(name.trim()); setName(""); await refreshDatabases(); setNotice({ message: "Database created successfully" }); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    const remove = async database => { if (!window.confirm(`Delete database ${database}?`)) return; try { await api.deleteDatabase(database); await refreshDatabases(); setNotice({ message: "Database deleted" }); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    return <div className="page-stack"><Header title="Databases"><div className="inline-form"><input value={name} placeholder="database name" onChange={event => setName(event.target.value)} /><button className="button primary" disabled={!name.trim()} onClick={create}><Plus size={15} />Create</button></div></Header><div className="resource-grid">{databases.map(database => <div className={`resource-card ${selectedDatabase === database ? "selected" : ""}`} key={database}><div className="resource-icon"><Database size={18} /></div><div><strong>{database}</strong><span>Persistent JSON database</span></div><span className="pill blue">{selectedDatabase === database ? "CURRENT" : "READY"}</span><button className="button secondary small" onClick={() => setSelectedDatabase(database)}>Use</button><button className="icon-button danger" onClick={() => remove(database)} title="Delete database"><Trash2 size={16} /></button></div>)}{!databases.length && <Empty>No databases yet. Create one to begin.</Empty>}</div></div>;
}

export function Collections() {
    const { selectedDatabase, collections, setSelectedCollection, setCollections, setNotice } = useApp(); const [name, setName] = useState("");
    if (!selectedDatabase) return <div className="page-stack"><Header title="Collections" /><ScopeRequired /></div>;
    const create = async () => { try { await api.createCollection(selectedDatabase, name.trim()); const data = await api.getCollections(selectedDatabase); setCollections(data.collections || []); setName(""); setNotice({ message: "Collection created successfully" }); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    const remove = async collection => { if (!window.confirm(`Delete collection ${collection}?`)) return; try { await api.deleteCollection(selectedDatabase, collection); const data = await api.getCollections(selectedDatabase); setCollections(data.collections || []); setNotice({ message: "Collection deleted" }); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    return <div className="page-stack"><Header title={`Collections / ${selectedDatabase}`}><div className="inline-form"><input value={name} placeholder="collection name" onChange={event => setName(event.target.value)} /><button className="button primary" disabled={!name.trim()} onClick={create}><Plus size={15} />Create</button></div></Header><div className="resource-grid">{collections.map(collection => <div className="resource-card selected" key={collection}><div className="resource-icon"><FileJson size={18} /></div><div><strong>{collection}</strong><span>JSON document collection</span></div><button className="button primary small" onClick={() => setSelectedCollection(collection)}>Open</button><button className="icon-button danger" onClick={() => remove(collection)} title="Delete collection"><Trash2 size={16} /></button></div>)}{!collections.length && <Empty>No collections in this database.</Empty>}</div></div>;
}

export function Documents() {
    const { selectedDatabase, selectedCollection, setNotice } = useApp(); const [records, setRecords] = useState([]); const [search, setSearch] = useState(""); const [editor, setEditor] = useState(null); const [json, setJson] = useState("{}\n"); const [loading, setLoading] = useState(false);
    const reload = useCallback(async () => { if (!selectedDatabase || !selectedCollection) return; setLoading(true); try { const data = await api.getDocuments(selectedDatabase, selectedCollection); setRecords(data.data || []); } catch (error) { setNotice({ type: "error", message: error.message }); } finally { setLoading(false); } }, [selectedDatabase, selectedCollection, setNotice]);
    useEffect(() => { reload(); }, [reload]);
    const visible = useMemo(() => records.filter(record => !search || JSON.stringify(record).toLowerCase().includes(search.toLowerCase())), [records, search]);
    const save = async () => { try { const value = JSON.parse(json); if (editor === "new") await api.insertDocument(selectedDatabase, selectedCollection, value); else await api.updateDocument(selectedDatabase, selectedCollection, editor.id, value); setEditor(null); await reload(); setNotice({ message: "Document saved successfully" }); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    const remove = async id => { if (!window.confirm(`Delete document ${id}?`)) return; try { await api.deleteDocument(selectedDatabase, selectedCollection, id); await reload(); setNotice({ message: "Document deleted" }); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    if (!selectedDatabase || !selectedCollection) return <div className="page-stack"><Header title="Documents" /><ScopeRequired /></div>;
    return <div className="page-stack"><Header title={`${selectedCollection} / Documents`}><div className="search-box"><input placeholder="Search JSON" value={search} onChange={event => setSearch(event.target.value)} /></div><button className="button primary" onClick={() => { setJson("{}\n"); setEditor("new"); }}><Plus size={15} />Insert document</button></Header><div className="panel table-panel"><div className="table-meta"><span>{loading ? "Loading..." : `${visible.length} matching documents`}</span><button className="icon-button" onClick={reload} title="Refresh"><RefreshCw size={16} /></button></div>{visible.length ? <div className="table-wrap"><table><thead><tr><th>ID</th><th>JSON preview</th><th>Fields</th><th>Actions</th></tr></thead><tbody>{visible.map(record => <tr key={record.id}><td><code>{record.id}</code></td><td><pre className="cell-json">{JSON.stringify(record, null, 2)}</pre></td><td><code>{Object.keys(record).join(", ")}</code></td><td><button className="icon-button" title="Edit" onClick={() => { setEditor(record); setJson(JSON.stringify(record, null, 2)); }}><FileJson size={16} /></button><button className="icon-button danger" title="Delete" onClick={() => remove(record.id)}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div> : <Empty>{loading ? "Loading documents..." : "No documents match this search."}</Empty>}</div>{editor && <div className="modal-backdrop"><div className="modal"><div className="modal-header"><h3>{editor === "new" ? "Insert JSON" : `Edit document ${editor.id}`}</h3><button className="icon-button" onClick={() => setEditor(null)}><X size={18} /></button></div><JsonEditor value={json} onChange={setJson} /><div className="modal-actions"><button className="button secondary" onClick={() => setEditor(null)}>Cancel</button><button className="button primary" onClick={save}>Save document</button></div></div></div>}</div>;
}

export function QueryConsole() {
    const { selectedDatabase, selectedCollection, setNotice } = useApp(); const [json, setJson] = useState("{}\n"); const [result, setResult] = useState(null); const [plan, setPlan] = useState(null);
    if (!selectedDatabase || !selectedCollection) return <div className="page-stack"><Header title="Query console" /><ScopeRequired /></div>;
    const run = async explain => { try { const filter = JSON.parse(json); if (explain) setPlan(await api.explain(selectedDatabase, selectedCollection, filter)); else setResult(await api.query(selectedDatabase, selectedCollection, filter)); } catch (error) { setNotice({ type: "error", message: error.message }); } };
    return <div className="page-stack"><div className="console-grid"><div className="panel"><div className="eyebrow">{selectedDatabase} / {selectedCollection}</div><h3>Query filter</h3><JsonEditor value={json} onChange={setJson} label="JSON query" /><div className="button-row"><button className="button primary" onClick={() => run(false)}><Play size={15} />Execute</button><button className="button secondary" onClick={() => run(true)}>Explain</button></div></div><div className="panel"><Header title={plan ? "Execution plan" : "Results"} />{plan ? <pre className="json-output">{JSON.stringify(plan, null, 2)}</pre> : result ? <pre className="json-output">{JSON.stringify(result, null, 2)}</pre> : <Empty>Run a query to see backend results.</Empty>}</div></div></div>;
}

export function Indexes() { const { selectedDatabase, selectedCollection, setNotice } = useApp(); const [indexes, setIndexes] = useState([]); const [field, setField] = useState(""); const [unique, setUnique] = useState(false); useEffect(() => { if (selectedDatabase && selectedCollection) api.getIndexes(selectedDatabase, selectedCollection).then(data => setIndexes(data.indexes || [])).catch(error => setNotice({ type: "error", message: error.message })); }, [selectedDatabase, selectedCollection, setNotice]); if (!selectedDatabase || !selectedCollection) return <div className="page-stack"><Header title="Indexes" /><ScopeRequired /></div>; const create = async () => { try { await api.createIndex(selectedDatabase, selectedCollection, field.trim(), { unique }); setIndexes((await api.getIndexes(selectedDatabase, selectedCollection)).indexes || []); setField(""); setUnique(false); setNotice({ message: "Index created successfully" }); } catch (error) { setNotice({ type: "error", message: error.message }); } }; return <div className="page-stack"><Header title={`Indexes / ${selectedCollection}`}><div className="inline-form"><input placeholder="field name" value={field} onChange={event => setField(event.target.value)} /><label className="check-field"><input type="checkbox" checked={unique} onChange={event => setUnique(event.target.checked)} /> unique</label><button className="button primary" disabled={!field.trim()} onClick={create}><Plus size={15} />Create</button></div></Header><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Field</th><th>Type</th><th>Unique</th><th /></tr></thead><tbody>{indexes.map(index => <tr key={index.field}><td><strong>{index.field}</strong></td><td>{index.type}</td><td>{String(index.unique)}</td><td><button className="icon-button danger" title={`Delete ${index.field} index`} onClick={async () => { try { await api.deleteIndex(selectedDatabase, selectedCollection, index.field); setIndexes(indexes.filter(item => item.field !== index.field)); } catch (error) { setNotice({ type: "error", message: error.message }); } }}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>{!indexes.length && <Empty>No indexes configured.</Empty>}</div></div>; }

export function Schema() { const { selectedDatabase, selectedCollection, setNotice } = useApp(); const [json, setJson] = useState("{}"); useEffect(() => { if (selectedDatabase && selectedCollection) api.getSchema(selectedDatabase, selectedCollection).then(data => setJson(JSON.stringify(data.schema || {}, null, 2))).catch(error => setNotice({ type: "error", message: error.message })); }, [selectedDatabase, selectedCollection, setNotice]); if (!selectedDatabase || !selectedCollection) return <div className="page-stack"><Header title="Schema" /><ScopeRequired /></div>; const save = async () => { try { await api.updateSchema(selectedDatabase, selectedCollection, JSON.parse(json)); setNotice({ message: "Schema updated successfully" }); } catch (error) { setNotice({ type: "error", message: error.message }); } }; const remove = async () => { if (!window.confirm(`Delete the schema for ${selectedCollection}?`)) return; try { await api.deleteSchema(selectedDatabase, selectedCollection); setJson("{}"); setNotice({ message: "Schema deleted" }); } catch (error) { setNotice({ type: "error", message: error.message }); } }; return <div className="page-stack"><Header title={`Schema / ${selectedCollection}`} /><div className="panel"><JsonEditor value={json} onChange={setJson} label="Schema rules" /><div className="button-row"><button className="button primary" onClick={save}>Save schema</button><button className="button secondary" onClick={remove}>Delete schema</button></div></div></div>; }

export function Transactions() { const { selectedDatabase, setNotice } = useApp(); const [transactions, setTransactions] = useState([]); const [selected, setSelected] = useState(null); const reload = useCallback(() => api.getTransactions(selectedDatabase).then(data => setTransactions(data.transactions || [])).catch(error => setNotice({ type: "error", message: error.message })), [selectedDatabase, setNotice]); useEffect(() => { if (selectedDatabase) reload(); }, [selectedDatabase, reload]); if (!selectedDatabase) return <div className="page-stack"><Header title="Transactions" /><ScopeRequired /></div>; const begin = async () => { try { const data = await api.beginTransaction(selectedDatabase); setSelected(data.transaction); reload(); } catch (error) { setNotice({ type: "error", message: error.message }); } }; return <div className="page-stack"><Header title="Transactions"><button className="button primary" onClick={begin}><Plus size={15} />Begin</button></Header><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>ID</th><th>Status</th><th>Operations</th></tr></thead><tbody>{transactions.map(transaction => <tr key={transaction.id}><td><button className="text-link" onClick={() => setSelected(transaction)}>{transaction.id}</button></td><td>{transaction.status}</td><td>{transaction.operations}</td></tr>)}</tbody></table></div>{!transactions.length && <Empty>No active transactions.</Empty>}</div>{selected && <div className="modal-backdrop"><div className="modal compact"><div className="modal-header"><h3>{selected.id}</h3><button className="icon-button" onClick={() => setSelected(null)}><X size={18} /></button></div><pre className="json-output">{JSON.stringify(selected, null, 2)}</pre><div className="modal-actions"><button className="button secondary" onClick={async () => { await api.rollbackTransaction(selectedDatabase, selected.id); setSelected(null); reload(); }}>Rollback</button><button className="button primary" onClick={async () => { await api.commitTransaction(selectedDatabase, selected.id); setSelected(null); reload(); }}>Commit</button></div></div></div>}</div>; }

export function Logs() { const { selectedDatabase } = useApp(); const [data, setData] = useState({ records: [] }); useEffect(() => { if (selectedDatabase) api.getWal(selectedDatabase).then(setData); }, [selectedDatabase]); if (!selectedDatabase) return <div className="page-stack"><Header title="WAL / Logs" /><ScopeRequired /></div>; return <div className="page-stack"><Header title="WAL / Logs"><button className="button secondary" onClick={() => api.getWal(selectedDatabase).then(setData)}><RefreshCw size={15} />Refresh</button></Header><div className="panel"><pre className="json-output">{JSON.stringify(data.records || [], null, 2)}</pre></div></div>; }